# Generated by Django 3.2.4 on 2021-06-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiangou_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
